/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as MeuPartoIaRouteImport } from './routes/meu-parto-ia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardPublicoRouteImport } from './routes/dashboard-publico'
import { Route as AplataformaRouteImport } from './routes/aplataforma'
import { Route as IndexRouteImport } from './routes/index'

const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPartoIaRoute = MeuPartoIaRouteImport.update({
  id: '/meu-parto-ia',
  path: '/meu-parto-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicoRoute = DashboardPublicoRouteImport.update({
  id: '/dashboard-publico',
  path: '/dashboard-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const AplataformaRoute = AplataformaRouteImport.update({
  id: '/aplataforma',
  path: '/aplataforma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplataforma': typeof AplataformaRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/publicacoes': typeof PublicacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplataforma': typeof AplataformaRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/publicacoes': typeof PublicacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplataforma': typeof AplataformaRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/publicacoes': typeof PublicacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aplataforma'
    | '/dashboard-publico'
    | '/login'
    | '/meu-parto-ia'
    | '/publicacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplataforma'
    | '/dashboard-publico'
    | '/login'
    | '/meu-parto-ia'
    | '/publicacoes'
  id:
    | '__root__'
    | '/'
    | '/aplataforma'
    | '/dashboard-publico'
    | '/login'
    | '/meu-parto-ia'
    | '/publicacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplataformaRoute: typeof AplataformaRoute
  DashboardPublicoRoute: typeof DashboardPublicoRoute
  LoginRoute: typeof LoginRoute
  MeuPartoIaRoute: typeof MeuPartoIaRoute
  PublicacoesRoute: typeof PublicacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-parto-ia': {
      id: '/meu-parto-ia'
      path: '/meu-parto-ia'
      fullPath: '/meu-parto-ia'
      preLoaderRoute: typeof MeuPartoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-publico': {
      id: '/dashboard-publico'
      path: '/dashboard-publico'
      fullPath: '/dashboard-publico'
      preLoaderRoute: typeof DashboardPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplataforma': {
      id: '/aplataforma'
      path: '/aplataforma'
      fullPath: '/aplataforma'
      preLoaderRoute: typeof AplataformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplataformaRoute: AplataformaRoute,
  DashboardPublicoRoute: DashboardPublicoRoute,
  LoginRoute: LoginRoute,
  MeuPartoIaRoute: MeuPartoIaRoute,
  PublicacoesRoute: PublicacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
