/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MeuPartoIaRouteImport } from './routes/meu-parto-ia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardPublicoRouteImport } from './routes/dashboard-publico'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPartoIaRoute = MeuPartoIaRouteImport.update({
  id: '/meu-parto-ia',
  path: '/meu-parto-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicoRoute = DashboardPublicoRouteImport.update({
  id: '/dashboard-publico',
  path: '/dashboard-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard-publico': typeof DashboardPublicoRoute
  '/login': typeof LoginRoute
  '/meu-parto-ia': typeof MeuPartoIaRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard-publico' | '/login' | '/meu-parto-ia' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard-publico' | '/login' | '/meu-parto-ia' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/dashboard-publico'
    | '/login'
    | '/meu-parto-ia'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardPublicoRoute: typeof DashboardPublicoRoute
  LoginRoute: typeof LoginRoute
  MeuPartoIaRoute: typeof MeuPartoIaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-parto-ia': {
      id: '/meu-parto-ia'
      path: '/meu-parto-ia'
      fullPath: '/meu-parto-ia'
      preLoaderRoute: typeof MeuPartoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-publico': {
      id: '/dashboard-publico'
      path: '/dashboard-publico'
      fullPath: '/dashboard-publico'
      preLoaderRoute: typeof DashboardPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardPublicoRoute: DashboardPublicoRoute,
  LoginRoute: LoginRoute,
  MeuPartoIaRoute: MeuPartoIaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
